-- CreateTable
CREATE TABLE "daily_logs" (
    "id" SERIAL NOT NULL,
    "date" DATE NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "restingO2Sat" INTEGER,
    "restingHr" INTEGER,
    "inogenSetting" INTEGER,
    "symptomsScore" INTEGER,
    "seatedMarching" BOOLEAN NOT NULL DEFAULT false,
    "shoulderRolls" BOOLEAN NOT NULL DEFAULT false,
    "diaphragmaticBreathing" BOOLEAN NOT NULL DEFAULT false,
    "pursedLipBreathingWarmup" BOOLEAN NOT NULL DEFAULT false,
    "bicepCurlsDone" BOOLEAN NOT NULL DEFAULT false,
    "bicepCurlsWeight" TEXT,
    "bicepCurlsReps" TEXT,
    "tricepExtDone" BOOLEAN NOT NULL DEFAULT false,
    "tricepExtWeight" TEXT,
    "tricepExtReps" TEXT,
    "shoulderPressDone" BOOLEAN NOT NULL DEFAULT false,
    "shoulderPressWeight" TEXT,
    "shoulderPressReps" TEXT,
    "chestPressDone" BOOLEAN NOT NULL DEFAULT false,
    "chestPressBand" TEXT,
    "chestPressReps" TEXT,
    "seatedRowsDone" BOOLEAN NOT NULL DEFAULT false,
    "seatedRowsBand" TEXT,
    "seatedRowsReps" TEXT,
    "sitToStandsDone" BOOLEAN NOT NULL DEFAULT false,
    "sitToStandsReps" TEXT,
    "legLiftsDone" BOOLEAN NOT NULL DEFAULT false,
    "legLiftsReps" TEXT,
    "miniSquatsDone" BOOLEAN NOT NULL DEFAULT false,
    "miniSquatsReps" TEXT,
    "rowingDuration" INTEGER,
    "rowingAvgO2" INTEGER,
    "rowingLowO2" INTEGER,
    "rowingHr" INTEGER,
    "rowingInogen" INTEGER,
    "lightRowing" BOOLEAN NOT NULL DEFAULT false,
    "stretching" BOOLEAN NOT NULL DEFAULT false,
    "pursedLipBreathingCooldown" BOOLEAN NOT NULL DEFAULT false,
    "recoveryO2" INTEGER,
    "recoveryHr" INTEGER,
    "notes" TEXT,

    CONSTRAINT "daily_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "daily_logs_date_key" ON "daily_logs"("date");
